## Context

Starting in 2008, every year Forbes Magazine publishes a list of America's best colleges. When it comes to the question everyone seems to be asking, “Is college worth it? this published list of colleges comes handy to take a decision based on student's requirement or desire.

The mission of the college ranking by Forbes Magazine is to conduct an annual review of the undergraduate institutions that deliver the top academics, best experiences, career success and lowest debt. Whether a school is in the Top 10 or near the bottom of the list, the 650 colleges are the best in the country.

For most families, choosing a four-year college is one of the biggest and most expensive decisions they can make. For students, this time of their life may layout their future plans. So choose carefully.

## About Data

The data set contains the rankings of 650 Unites States colleges along with various other statistics pertaining to each school.

<img src ="https://i.ibb.co/sKwQjfw/Stanford.jpg" width=80% height =40%></img>

### Load required packages

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Load the data into pandas dataframe and view the details

In [29]:
import pandas as pd

df = pd.read_csv("AmericasTopColleges.csv")

df.head()

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,www.harvard.edu
1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,www.stanford.edu
2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,www.yale.edu
3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,web.mit.edu
4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,www.princeton.edu

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Rank                      650 non-null    int64
 1   Name                      650 non-null    object
 2   City                      650 non-null    object
 3   State                     650 non-null    object
 4   Public/Private            650 non-null    object
 5   Undergraduate Population  650 non-null    int64
 6   Student Population        650 non-null    int64
 7   Net Price                 648 non-null    float64
 8   Average Grant Aid         646 non-null    float64
 9   Total Annual Cost         650 non-null    int64
 10  Alumni Salary             635 non-null    float64
 11  Acceptance Rate           648 non-null    float64
 12  SAT Lower                 551 non-null    float64
 13  SAT Upper                 551 non-null    float64
 14  ACT Lower                 553 non-null    float64
 15  ACT Upper                 553 non-null    float64
 16  Website                   645 non-null    object
dtypes: float64(8), int64(4), object(5)
memory usage: 86.5+ KB

In [6]:
df.describe()

,Rank,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper
count,650.00000,650.000000,650.000000,648.000000,646.000000,650.000000,635.000000,648.000000,551.000000,551.000000,553.000000,553.000000
mean,325.50000,10002.692308,12022.290769,22336.947531,20031.208978,50330.175385,98851.968504,61.597222,1110.145191,1308.078040,23.278481,28.441230
std,187.78312,11162.172430,13175.091581,8269.912032,11175.869976,13223.055038,14335.249458,22.024781,127.744079,113.553237,3.729318,3.058115
min,1.00000,185.000000,386.000000,0.000000,2975.000000,0.000000,70700.000000,5.000000,820.000000,1060.000000,15.000000,20.000000
25%,163.25000,2020.250000,2240.750000,16410.000000,9288.250000,39917.000000,88600.000000,48.000000,1020.000000,1230.000000,21.000000,26.000000
50%,325.50000,4503.000000,6269.000000,21989.000000,19605.000000,50265.000000,96400.000000,67.000000,1080.000000,1290.000000,22.000000,28.000000
75%,487.75000,15657.000000,17788.000000,27580.500000,27474.500000,60771.750000,105600.000000,78.000000,1180.000000,1380.000000,25.000000,31.000000
max,650.00000,65100.000000,75044.000000,47270.000000,50897.000000,75735.000000,158200.000000,100.000000,1530.000000,1590.000000,34.000000,35.000000

### Dimension of the data

*'shape'* is a property associated with DataFrame. It returns a tuple representing the dimensionality of the DataFrame. First value is giving number of rows and second value is giving number of columns.

In [7]:
df.shape

(650, 17)

### Datatype of the fields in the data

In [8]:
df.dtypes

Rank                          int64
Name                         object
City                         object
State                        object
Public/Private               object
Undergraduate Population      int64
Student Population            int64
Net Price                   float64
Average Grant Aid           float64
Total Annual Cost             int64
Alumni Salary               float64
Acceptance Rate             float64
SAT Lower                   float64
SAT Upper                   float64
ACT Lower                   float64
ACT Upper                   float64
Website                      object
dtype: object

### Check the missing values in the data
'isnull()' method detects missing values. It returns a boolean same-sized object indicating if the values are NA. NA values, gets mapped to True values.Everything else gets mapped to False values.

'sum()' method followed by 'isnull()' adds up all the True instances per column to give a summary of missing values per column

In [9]:
df.isnull().sum()

Rank                         0
Name                         0
City                         0
State                        0
Public/Private               0
Undergraduate Population     0
Student Population           0
Net Price                    2
Average Grant Aid            4
Total Annual Cost            0
Alumni Salary               15
Acceptance Rate              2
SAT Lower                   99
SAT Upper                   99
ACT Lower                   97
ACT Upper                   97
Website                      5
dtype: int64

In [10]:
df.isnull().sum().sum()

np.int64(420)

See the column names , with space

### Data Cleanup

Let's first drop all columns that are not need.

In [11]:
dff = df.copy()

In [12]:
dff.duplicated().sum()

np.int64(0)

In [13]:
dff.isnull().sum()

Rank                         0
Name                         0
City                         0
State                        0
Public/Private               0
Undergraduate Population     0
Student Population           0
Net Price                    2
Average Grant Aid            4
Total Annual Cost            0
Alumni Salary               15
Acceptance Rate              2
SAT Lower                   99
SAT Upper                   99
ACT Lower                   97
ACT Upper                   97
Website                      5
dtype: int64

### Reset the index of the dataframe

In [14]:
dff.reset_index(drop=True, inplace=True)

### Check the first 5 rows of the dataset

In [15]:
dff.head(5)

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,www.harvard.edu
1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,www.stanford.edu
2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,www.yale.edu
3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,web.mit.edu
4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,www.princeton.edu

### Display the last five rows of the dataset

In [16]:
dff.tail(5)

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
645,646,New Mexico State University,Las Cruces,NM,Public,13379,14432,8625.0,9582.0,34720,96700.0,64.0,910.0,1160.0,18.0,23.0,www.nmsu.edu
646,647,Indiana State University,Terre Haute,IN,Public,13626,13763,13012.0,9297.0,32938,85600.0,85.0,900.0,1110.0,17.0,23.0,www.indstate.edu
647,648,Emory &amp; Henry College,Emory,VA,Private,1094,1226,19340.0,27155.0,48100,70700.0,72.0,988.0,1170.0,19.0,25.0,www.ehc.edu
648,649,Wells College,Aurora,NY,Private,488,516,22828.0,30207.0,55180,NaN,80.0,NaN,NaN,NaN,NaN,www.wells.edu
649,650,Catawba College,Salisbury,NC,Private,1336,1463,19807.0,23662.0,44921,78100.0,42.0,930.0,1100.0,18.0,23.0,www.catawba.edu

### Recheck the dimension and info of the data

In [17]:
dff.shape

(650, 17)

In [18]:
print("Rows:", dff.shape[0])
print("Columns:", dff.shape[1])

Rows: 650
Columns: 17

# Data Analysis

### Get Summary of Data

In [19]:
dff.describe(include='all')

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
count,650.00000,650,650,650,650,650.000000,650.000000,648.000000,646.000000,650.000000,635.000000,648.000000,551.000000,551.000000,553.000000,553.000000,645
unique,NaN,650,469,51,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,645
top,NaN,Catawba College,New York,NY,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,www.catawba.edu
freq,NaN,1,15,68,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
mean,325.50000,NaN,NaN,NaN,NaN,10002.692308,12022.290769,22336.947531,20031.208978,50330.175385,98851.968504,61.597222,1110.145191,1308.078040,23.278481,28.441230,NaN
std,187.78312,NaN,NaN,NaN,NaN,11162.172430,13175.091581,8269.912032,11175.869976,13223.055038,14335.249458,22.024781,127.744079,113.553237,3.729318,3.058115,NaN
min,1.00000,NaN,NaN,NaN,NaN,185.000000,386.000000,0.000000,2975.000000,0.000000,70700.000000,5.000000,820.000000,1060.000000,15.000000,20.000000,NaN
25%,163.25000,NaN,NaN,NaN,NaN,2020.250000,2240.750000,16410.000000,9288.250000,39917.000000,88600.000000,48.000000,1020.000000,1230.000000,21.000000,26.000000,NaN
50%,325.50000,NaN,NaN,NaN,NaN,4503.000000,6269.000000,21989.000000,19605.000000,50265.000000,96400.000000,67.000000,1080.000000,1290.000000,22.000000,28.000000,NaN
75%,487.75000,NaN,NaN,NaN,NaN,15657.000000,17788.000000,27580.500000,27474.500000,60771.750000,105600.000000,78.000000,1180.000000,1380.000000,25.000000,31.000000,NaN
max,650.00000,NaN,NaN,NaN,NaN,65100.000000,75044.000000,47270.000000,50897.000000,75735.000000,158200.000000,100.000000,1530.000000,1590.000000,34.000000,35.000000,NaN

# Sliciing of Data

### 1) Which are the top 5 colleges listed in the Forbes Magazine 2019?

We can also save the information in an object 'top5' and display it

In [20]:
top5 = dff.sort_values(by="Rank", ascending=True).head(5)
top5

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,www.harvard.edu
1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,www.stanford.edu
2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,www.yale.edu
3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,web.mit.edu
4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,www.princeton.edu

### 2) Which state and city do the top 5 colleges belong to?

In [21]:
top5 = dff.sort_values(by="Rank").head(5)

top5[["Name", "City", "State"]]

                                    Name       City State
0                     Harvard University  Cambridge    MA
1                    Stanford University   Stanford    CA
2                        Yale University  New Haven    CT
3  Massachusetts Institute of Technology  Cambridge    MA
4                   Princeton University  Princeton    NJ

### 3) How many states and which all states have the colleges listed by Forbes?

In [22]:
num_states = dff["State"].nunique()
states = sorted(dff["State"].unique())

print("Number of States:", num_states)
print("States:", states)

Number of States: 51
States: ['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']

### 4) In all how many private and public colleges are there in the given list?

In [23]:
dff['Public/Private'].value_counts()

Public/Private
Private    400
Public     250
Name: count, dtype: int64

### 5) From the list how many colleges are there within each State? Which State has highest number of colleges?

In [24]:
dff['State'].value_counts()

State
NY    68
CA    56
PA    40
MA    31
OH    29
TX    25
IL    25
FL    20
VA    20
NC    19
IN    19
MN    19
MI    17
TN    14
MD    14
GA    14
MO    13
NJ    13
WI    13
IA    13
KY    12
WA    12
CO    12
OR    11
CT    10
SC     9
AL     8
LA     8
RI     7
ME     6
OK     6
NE     6
DC     5
MS     5
VT     5
UT     5
AR     5
NM     4
AZ     4
MT     4
ID     4
SD     4
NH     3
KS     3
ND     2
AK     2
NV     2
DE     1
WY     1
HI     1
WV     1
Name: count, dtype: int64

### 6) What is percentage of undergraduates in each college? (Add a new field to calculate)

In [31]:
df["Undergraduate Percentage"] = (
    df["Undergraduate Population"] / df["Student Population"]
) * 100

In [32]:
df[["Name", "Undergraduate Percentage"]]

                                      Name  Undergraduate Percentage
0                       Harvard University                 44.485861
1                      Stanford University                 47.918330
2                          Yale University                 49.969169
3    Massachusetts Institute of Technology                 40.816327
4                     Princeton University                 68.403239
..                                     ...                       ...
645            New Mexico State University                 92.703714
646               Indiana State University                 99.004577
647              Emory &amp; Henry College                 89.233279
648                          Wells College                 94.573643
649                        Catawba College                 91.319207

[650 rows x 2 columns]

### 7) Which are the 5 colleges with highest percentage of undergraduates?

In [34]:
top5_undergrad = df.sort_values(
    by="Undergraduate Percentage",
    ascending=False
).head(5)

In [35]:
top5_undergrad[["Name", "Undergraduate Percentage"]]

                                       Name  Undergraduate Percentage
570  University of Texas, Rio Grande Valley                 99.992808
253            Saint John's University (MN)                 99.944934
565                      Oakland University                 99.937930
364                    Salisbury University                 99.919734
345                     St. Norbert College                 99.861432

### 8) 5 colleges that receive highest Average Grant Aid?

In [36]:
top5_grant_aid = df.sort_values(
    by="Average Grant Aid",
    ascending=False
).head(5)

In [37]:
top5_grant_aid[["Name", "Average Grant Aid"]]

                   Name  Average Grant Aid
2       Yale University            50897.0
1   Stanford University            50134.0
0    Harvard University            49870.0
27      Amherst College            49467.0
13  Columbia University            49185.0


### 9) What is the average Undergraduate population in State of 'CA'?

In [38]:
id="q1"
ca_avg_undergrad = df[df["State"] == "CA"]["Undergraduate Population"].mean()

ca_avg_undergrad

np.float64(13186.910714285714)

### 10) Which are the colleges where chances of admission is high?

In [41]:
top5_admission = df.sort_values(
    by="Acceptance Rate",
    ascending=False
).head(15)

top5_admission[["Name", "Acceptance Rate"]]

                                   Name  Acceptance Rate
605        University of Texas, El Paso            100.0
626  University of Southern Mississippi             98.0
637             Wright State University             97.0
346               University of Wyoming             97.0
636                    Marlboro College             97.0
307              University of Kentucky             96.0
599         Western Kentucky University             95.0
412      Brigham Young University-Idaho             95.0
306             Transylvania University             95.0
386                    Covenant College             95.0
608                University of Toledo             94.0
365             Kansas State University             94.0
596            Wichita State University             94.0
572             Oral Roberts University             93.0
341            Westminster College (UT)             93.0

### 11) Find if there are any 'Art' colleges in the list

To find a specific string value 'Art' we will use the 'contains()' method. We will pass the string in the paranthesis which needs to be located in the dataframe variable.

In [42]:
art_colleges = df[df["Name"].str.contains("Art", case=False, na=False)]

art_colleges[["Name"]]

                                  Name
9                    Dartmouth College
24                  Swarthmore College
189  Hobart and William Smith Colleges
302  Maryland Institute College of Art
369            Sacred Heart University
401   California Institute of the Arts
541             University of Hartford
578                   Hartwick College
594                   Carthage College

### 12) Lets divide the Alumni Salary equally into 3 buckets (Low Salary - L; Medium Salary - M; High Salary - H ) and check which colleges falls in 'H' bucket

In [43]:
df["Salary Bucket"] = pd.qcut(
    df["Alumni Salary"],
    q=3,
    labels=["L", "M", "H"]
)

In [44]:
high_salary_colleges = df[df["Salary Bucket"] == "H"]

high_salary_colleges[["Name", "Alumni Salary", "Salary Bucket"]]

                                          Name  Alumni Salary Salary Bucket
0                           Harvard University       146800.0             H
1                          Stanford University       145200.0             H
2                              Yale University       138300.0             H
3        Massachusetts Institute of Technology       155200.0             H
4                         Princeton University       139400.0             H
..                                         ...            ...           ...
474        University of Alabama in Huntsville       103900.0             H
488                              Touro College       103100.0             H
491      California State University, East Bay       103500.0             H
502          Lawrence Technological University       108400.0             H
575  Montana Tech of the University of Montana       112600.0             H

[211 rows x 3 columns]

Take a copy of the original DataFrame to work on

'cut()' function bins values into discrete intervals. 'cut()' function is used when you need to segment and sort data values into bins. This function is also useful for going from a continuous variable to a categorical variable.

In the above code we have created 3 bins using 'Alumni Salary' column. Lowest range of salary is labelled as 'L', middle range is labelled as 'M' and highest range of salary is labelled as 'H'. These labels are saved in a new column 'Alumni Sal Level'.

Note: The entire range of the 'Alumni Salary' has been divided into 3 equal ranges i.e. 3 bins

In [50]:
df["Alumni Sal Level"] = pd.cut(
    df["Alumni Salary"],
    bins=3,
    labels=["L", "M", "H"]
)
print(df)

     Rank                                   Name         City State  \
0       1                     Harvard University    Cambridge    MA
1       2                    Stanford University     Stanford    CA
2       3                        Yale University    New Haven    CT
3       4  Massachusetts Institute of Technology    Cambridge    MA
4       5                   Princeton University    Princeton    NJ
..    ...                                    ...          ...   ...
645   646            New Mexico State University   Las Cruces    NM
646   647               Indiana State University  Terre Haute    IN
647   648              Emory &amp; Henry College        Emory    VA
648   649                          Wells College       Aurora    NY
649   650                        Catawba College    Salisbury    NC

    Public/Private  Undergraduate Population  Student Population  Net Price  \
0          Private                     13844               31120    14327.0
1          Private                      8402               17534    13261.0
2          Private                      6483               12974    18627.0
3          Private                      4680               11466    20771.0
4          Private                      5659                8273     9327.0
..             ...                       ...                 ...        ...
645         Public                     13379               14432     8625.0
646         Public                     13626               13763    13012.0
647        Private                      1094                1226    19340.0
648        Private                       488                 516    22828.0
649        Private                      1336                1463    19807.0

     Average Grant Aid  Total Annual Cost  Alumni Salary  Acceptance Rate  \
0              49870.0              69600       146800.0              5.0
1              50134.0              69109       145200.0              5.0
2              50897.0              71290       138300.0              7.0
3              43248.0              67430       155200.0              7.0
4              48088.0              66150       139400.0              6.0
..                 ...                ...            ...              ...
645             9582.0              34720        96700.0             64.0
646             9297.0              32938        85600.0             85.0
647            27155.0              48100        70700.0             72.0
648            30207.0              55180            NaN             80.0
649            23662.0              44921        78100.0             42.0

     SAT Lower  SAT Upper  ACT Lower  ACT Upper            Website  \
0       1460.0     1590.0       32.0       35.0    www.harvard.edu
1       1390.0     1540.0       32.0       35.0   www.stanford.edu
2       1460.0     1580.0       32.0       35.0       www.yale.edu
3       1490.0     1570.0       33.0       35.0        web.mit.edu
4       1430.0     1570.0       31.0       35.0  www.princeton.edu
..         ...        ...        ...        ...                ...
645      910.0     1160.0       18.0       23.0       www.nmsu.edu
646      900.0     1110.0       17.0       23.0   www.indstate.edu
647      988.0     1170.0       19.0       25.0        www.ehc.edu
648        NaN        NaN        NaN        NaN      www.wells.edu
649      930.0     1100.0       18.0       23.0    www.catawba.edu

     Undergraduate Percentage Salary Bucket Alumni Sal Level
0                   44.485861             H                H
1                   47.918330             H                H
2                   49.969169             H                H
3                   40.816327             H                H
4                   68.403239             H                H
..                        ...           ...              ...
645                 92.703714             M                L
646                 99.004577             L                L
647                 89.233279             L                L
648                 94.573643           NaN              NaN
649                 91.319207             L                L

[650 rows x 20 columns]

In [51]:
df["Salary Bucket"] = pd.qcut(
    df["Alumni Salary"],
    q=3,
    labels=["L", "M", "H"]
)
print(df)

     Rank                                   Name         City State  \
0       1                     Harvard University    Cambridge    MA
1       2                    Stanford University     Stanford    CA
2       3                        Yale University    New Haven    CT
3       4  Massachusetts Institute of Technology    Cambridge    MA
4       5                   Princeton University    Princeton    NJ
..    ...                                    ...          ...   ...
645   646            New Mexico State University   Las Cruces    NM
646   647               Indiana State University  Terre Haute    IN
647   648              Emory &amp; Henry College        Emory    VA
648   649                          Wells College       Aurora    NY
649   650                        Catawba College    Salisbury    NC

    Public/Private  Undergraduate Population  Student Population  Net Price  \
0          Private                     13844               31120    14327.0
1          Private                      8402               17534    13261.0
2          Private                      6483               12974    18627.0
3          Private                      4680               11466    20771.0
4          Private                      5659                8273     9327.0
..             ...                       ...                 ...        ...
645         Public                     13379               14432     8625.0
646         Public                     13626               13763    13012.0
647        Private                      1094                1226    19340.0
648        Private                       488                 516    22828.0
649        Private                      1336                1463    19807.0

     Average Grant Aid  Total Annual Cost  Alumni Salary  Acceptance Rate  \
0              49870.0              69600       146800.0              5.0
1              50134.0              69109       145200.0              5.0
2              50897.0              71290       138300.0              7.0
3              43248.0              67430       155200.0              7.0
4              48088.0              66150       139400.0              6.0
..                 ...                ...            ...              ...
645             9582.0              34720        96700.0             64.0
646             9297.0              32938        85600.0             85.0
647            27155.0              48100        70700.0             72.0
648            30207.0              55180            NaN             80.0
649            23662.0              44921        78100.0             42.0

     SAT Lower  SAT Upper  ACT Lower  ACT Upper            Website  \
0       1460.0     1590.0       32.0       35.0    www.harvard.edu
1       1390.0     1540.0       32.0       35.0   www.stanford.edu
2       1460.0     1580.0       32.0       35.0       www.yale.edu
3       1490.0     1570.0       33.0       35.0        web.mit.edu
4       1430.0     1570.0       31.0       35.0  www.princeton.edu
..         ...        ...        ...        ...                ...
645      910.0     1160.0       18.0       23.0       www.nmsu.edu
646      900.0     1110.0       17.0       23.0   www.indstate.edu
647      988.0     1170.0       19.0       25.0        www.ehc.edu
648        NaN        NaN        NaN        NaN      www.wells.edu
649      930.0     1100.0       18.0       23.0    www.catawba.edu

     Undergraduate Percentage Salary Bucket Alumni Sal Level
0                   44.485861             H                H
1                   47.918330             H                H
2                   49.969169             H                H
3                   40.816327             H                H
4                   68.403239             H                H
..                        ...           ...              ...
645                 92.703714             M                L
646                 99.004577             L                L
647                 89.233279             L                L
648                 94.573643           NaN              NaN
649                 91.319207             L                L

[650 rows x 20 columns]

### 13) Let's check the mean Alumni Salary at each level

In [46]:
df["Salary Bucket"] = pd.qcut(
    df["Alumni Salary"],
    q=3,
    labels=["L", "M", "H"]
)

In [47]:
df["Salary Bucket"].value_counts()

Salary Bucket
L    212
M    212
H    211
Name: count, dtype: int64

### 14) Let's create a new dataframe to further analyze the 28 colleges with High Alumni Salary

In [52]:
high_salary_df = df[df["Alumni Sal Level"] == "H"]

In [53]:
high_salary_df

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website,Undergraduate Percentage,Salary Bucket,Alumni Sal Level
0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,www.harvard.edu,44.485861,H,H
1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,www.stanford.edu,47.918330,H,H
2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,www.yale.edu,49.969169,H,H
3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,web.mit.edu,40.816327,H,H
4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,www.princeton.edu,68.403239,H,H
5,6,University of Pennsylvania,Philadelphia,PA,Private,13437,25367,24242.0,44801.0,71715,133900.0,9.0,1420.0,1560.0,32.0,35.0,www.upenn.edu,52.970395,H,H
7,8,California Institute of Technology,Pasadena,CA,Private,1002,2238,24245.0,41408.0,68901,151600.0,8.0,1530.0,1590.0,34.0,35.0,www.caltech.edu,44.772118,H,H
8,9,Duke University,Durham,NC,Private,7184,16130,35737.0,47836.0,71764,132100.0,10.0,1380.0,1540.0,31.0,35.0,www.duke.edu,44.538128,H,H
9,10,Dartmouth College,Hanover,NH,Private,4693,6509,30421.0,47171.0,71827,130900.0,10.0,1430.0,1560.0,30.0,34.0,www.dartmouth.edu,72.100169,H,H
12,13,"University of California, Berkeley",Berkeley,CA,Public,31133,41891,15859.0,18319.0,65003,131800.0,17.0,1260.0,1480.0,30.0,34.0,www.berkeley.edu,74.319066,H,H
17,18,University of Notre Dame,Notre Dame,IN,Private,8664,12467,28768.0,39590.0,69395,130500.0,19.0,1370.0,1520.0,32.0,34.0,www.nd.edu,69.495468,H,H
20,21,Rice University,Houston,TX,Private,4036,7022,20237.0,36387.0,63158,129500.0,16.0,1490.0,1580.0,33.0,35.0,www.rice.edu,57.476502,H,H
22,23,Harvey Mudd College,Claremont,CA,Private,847,861,34464.0,33782.0,74428,158200.0,15.0,1470.0,1570.0,33.0,35.0,www.hmc.edu,98.373984,H,H
23,24,United States Naval Academy,Annapolis,MD,Public,4495,4526,0.0,NaN,0,152800.0,8.0,1150.0,1370.0,NaN,NaN,www.usna.edu,99.315068,H,H
31,32,United States Military Academy,West Point,NY,Public,4491,4568,0.0,NaN,0,144000.0,10.0,1185.0,1400.0,23.0,28.0,www.usma.edu,98.314361,H,H
36,37,Carnegie Mellon University,Pittsburgh,PA,Private,6941,13869,31102.0,38163.0,70094,136100.0,22.0,1430.0,1560.0,32.0,35.0,www.cmu.edu,50.046867,H,H
42,43,United States Air Force Academy,Colorado Springs,CO,Public,4237,4276,0.0,NaN,0,138100.0,12.0,1210.0,1390.0,28.0,32.0,www.usafa.af.mil,99.087933,H,H
45,46,Colgate University,Hamilton,NY,Private,2894,3025,23310.0,45108.0,69860,130600.0,28.0,1310.0,1500.0,31.0,33.0,www.colgate.edu,95.669421,H,H
50,51,Santa Clara University,Santa Clara,CA,Private,5754,8629,33738.0,26671.0,69439,134700.0,54.0,1270.0,1440.0,28.0,32.0,www.scu.edu,66.682118,H,H
61,62,Babson College,Babson Park,MA,Private,2354,3329,35540.0,36717.0,68432,133800.0,24.0,1230.0,1410.0,27.0,32.0,www.babson.edu,70.711926,H,H
64,65,Georgia Institute of Technology,Atlanta,GA,Public,17223,29376,13291.0,12779.0,49366,133400.0,23.0,1090.0,1520.0,30.0,34.0,www.gatech.edu,58.629493,H,H
65,66,United States Merchant Marine Academy,Kings Point,NY,Public,912,975,6758.0,3597.0,8646,140700.0,22.0,1210.0,1280.0,26.0,28.0,www.usmma.edu,93.538462,H,H
66,67,Lehigh University,Bethlehem,PA,Private,5337,7017,34212.0,36014.0,65925,134100.0,25.0,1270.0,1430.0,29.0,32.0,www4.lehigh.edu/default.aspx,76.058145,H,H
92,93,Worcester Polytechnic Institute,Worcester,MA,Private,4654,6642,40376.0,19515.0,65046,135500.0,48.0,NaN,NaN,NaN,NaN,www.wpi.edu,70.069256,H,H
93,94,Colorado School of Mines,Golden,CO,Public,4811,6209,25710.0,10725.0,52698,139600.0,56.0,1310.0,1450.0,28.0,32.0,www.mines.edu,77.484297,H,H
109,110,Rose-Hulman Institute of Technology,Terre Haute,IN,Private,2245,2254,36906.0,20967.0,65031,135800.0,61.0,1260.0,1450.0,27.0,32.0,www.rose-hulman.edu,99.600710,H,H
112,113,Rensselaer Polytechnic Institute,Troy,NY,Private,6371,7592,34839.0,30596.0,70132,134100.0,43.0,1320.0,1500.0,28.0,32.0,www.rpi.edu,83.917281,H,H
151,152,Stevens Institute of Technology,Hoboken,NJ,Private,3144,6916,36620.0,25762.0,67204,139900.0,44.0,1320.0,1470.0,29.0,33.0,www.stevens.edu/sit,45.459803,H,H
206,207,Clarkson University,Potsdam,NY,Private,3335,4233,30563.0,32540.0,66106,130100.0,66.0,1143.0,1330.0,24.0,29.0,www.clarkson.edu,78.785731,H,H
308,309,California State University Maritime Academy,Vallejo,CA,Public,1090,1181,16416.0,7716.0,39962,129600.0,66.0,NaN,NaN,NaN,NaN,https://www.csum.edu/web/mycampus/home;jsessio...,92.294666,H,H
332,333,SUNY Maritime College,Throggs Neck,NY,Public,1778,1794,18413.0,7134.0,34958,140700.0,69.0,1100.0,1253.0,22.0,26.0,www.sunymaritime.edu,99.108138,H,H

Passing 'include = 'all'' to describe() method provides descriptive summary of all fields in the DataFrame. 'T' property transposes the table which helps in reviewing the statistics per column

In [54]:
high_salary_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Rank,31.0,NaN,NaN,NaN,65.387097,83.742732,1.0,9.5,37.0,80.0,333.0
Name,31,31,Harvard University,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,31,30,Cambridge,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,31,13,CA,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Public/Private,31,2,Private,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Undergraduate Population,31.0,NaN,NaN,NaN,6197.741935,5997.853599,847.0,3019.0,4680.0,6712.0,31133.0
Student Population,31.0,NaN,NaN,NaN,10008.483871,9875.565091,861.0,3781.0,6916.0,12720.5,41891.0
Net Price,31.0,NaN,NaN,NaN,22841.290323,11808.216109,0.0,15093.0,24242.0,33975.0,40376.0
Average Grant Aid,28.0,NaN,NaN,NaN,32340.535714,14681.882361,3597.0,20604.0,36200.5,44877.75,50897.0
Total Annual Cost,31.0,NaN,NaN,NaN,56860.290323,23227.487721,0.0,57928.0,67204.0,69730.0,74428.0
Alumni Salary,31.0,NaN,NaN,NaN,138290.322581,7841.911112,129500.0,132750.0,135800.0,140700.0,158200.0
Acceptance Rate,31.0,NaN,NaN,NaN,26.290323,21.101649,5.0,9.5,19.0,43.5,69.0
SAT Lower,29.0,NaN,NaN,NaN,1323.724138,126.060047,1090.0,1230.0,1320.0,1430.0,1530.0
SAT Upper,29.0,NaN,NaN,NaN,1482.862069,94.527292,1253.0,1430.0,1500.0,1560.0,1590.0
ACT Lower,28.0,NaN,NaN,NaN,29.535714,3.132649,22.0,28.0,30.0,32.0,34.0
ACT Upper,28.0,NaN,NaN,NaN,32.928571,2.508188,26.0,32.0,34.0,35.0,35.0
Website,31,31,www.harvard.edu,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Undergraduate Percentage,31.0,NaN,NaN,NaN,71.626208,20.262868,40.816327,51.508631,70.711926,92.916564,99.60071
Salary Bucket,31,1,H,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alumni Sal Level,31,1,H,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Happy Learning!!!